version: '3.8'

services:
  devops:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - ./data:/devops/data
      - ./debug:/devops/debug
      - ./logs:/devops/logs
      - ./projects:/devops/projects
      - ./results:/devops/results
      - ./scripts:/devops/scripts
    logging:
      driver: 'json-file'
      options:
        max-size: '10mb'
        max-file: '10'
