version: '3.8'

services:
  devops:
    build:
      context: .
      dockerfile: Dockerfile
    command: tail -f /dev/null
    volumes:
      - ./data:/devops/data
      - ./logs:/devops/logs
      - ./projects:/devops/projects
      - ./results:/devops/results
      - ./scripts:/devops/scripts
